[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["alanpq"]
repository = "https://github.com/alanpq/ritobin-lsp"

[workspace.dependencies]
paths = { path = "./crates/paths", version = "0.0.0" }
meta_wiki = { path = "./crates/meta_wiki/" }

log = "0.4.29"
tracing = "0.1.44"
thiserror = "2.0.18"
anyhow = "1.0.100"
itertools = "0.14.0"
rustc-hash = "2.1.1"

futures = "0.3.32"
crossbeam-channel = "0.5.15"
dashmap = { version = "6.1.0", features = ["serde"] }

tokio = { version = "1.50.0" }
reqwest = { version = "0.13.2" }

serde = { version = "1.0.228" }
serde_json = "1.0.148"
serde_with = "3.18.0"

camino = "1.1.10"

ltk_ritobin = { git = "https://github.com/LeagueToolkit/league-toolkit.git", features = ["serde"] }
ltk_meta = { git = "https://github.com/LeagueToolkit/league-toolkit.git", features = ["serde"] }
ltk_hash = { git = "https://github.com/LeagueToolkit/league-toolkit.git" }
ltk_mimir_cache = { git = "https://github.com/LeagueToolkit/Mimir.git" }
ltk_hashdb = { git = "https://github.com/LeagueToolkit/Mimir.git" }

[workspace.lints.rust]

[workspace.lints.clippy]
single_match = "allow"
