[package]
name = "ritobin-lsp"
version = "0.1.14"
edition = "2024"

[dependencies]
paths = { workspace = true, features = ["serde1"] }
meta_wiki.workspace = true

log.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3.22", default-features = false, features = [
    "registry",
    "fmt",
    "local-time",
    "std",
    "time",
    "tracing-log",
] }

thiserror.workspace = true
anyhow.workspace = true
itertools.workspace = true
rustc-hash.workspace = true

serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_with.workspace = true

ltk_ritobin = { workspace = true, features = ["serde"] }
ltk_meta = { workspace = true, features = ["serde"] }
ltk_hash.workspace = true
ltk_mimir_cache.workspace = true
ltk_hashdb.workspace = true

futures.workspace = true
crossbeam-channel.workspace = true
dashmap = { workspace = true, features = ["serde"] }
arc-swap = "1.9.2"

tokio = { workspace = true, features = ["full"] }
reqwest = { workspace = true, features = ["json", "stream", "blocking"] }

lsp-server = "0.7.9"
lsp-types = { version = "=0.95.0", features = ["proposed"] }

clap = { version = "4.5.54", features = ["derive"] }
semver = "1.0.27"
directories-next = "2.0.0"
memmap = "0.7.0"
fst = "0.4.7"
imara-diff = "0.2.0"
