on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-lockfiles:
    if: contains(github.head_ref, 'release-please')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
      - run: cargo generate-lockfile

      - uses: actions/setup-node@v4

      - working-directory: editors/code
        run: npm install --package-lock-only

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Cargo.lock editors/code/package-lock.json
          git commit -m "chore: update lockfiles" || true
          git push
